# Generated by Django 3.2.4 on 2021-07-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AddField(
            model_name='posts',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime'),
        ),
        migrations.AddField(
            model_name='posts',
            name='owner_user',
            field=models.CharField(default='Jon Doy', max_length=256, verbose_name='owner'),
        ),
    ]
