# Generated by Django 3.2.4 on 2021-07-01 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_posts', '0002_auto_20210701_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='comments')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='datetime')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module_posts.posts')),
            ],
        ),
    ]
